import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MapContainer from "./components/MapContainer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Add if user not logged in logic, force login
        else showmap */}
        <MapContainer />
      </main>
    </div>
  );
};

export default Home;
